// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmT3s0GgRj1CxwRL7UW68EE2xh6XPTwjY',
    appId: '1:793243991391:web:ae4faae9f8536f2e064aea',
    messagingSenderId: '793243991391',
    projectId: 'cpu-dining',
    authDomain: 'cpu-dining.firebaseapp.com',
    storageBucket: 'cpu-dining.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDPBbl561iqNx7p7yu9eG6V5s8QXIAjco',
    appId: '1:793243991391:android:02eab5dcbac07d0a064aea',
    messagingSenderId: '793243991391',
    projectId: 'cpu-dining',
    storageBucket: 'cpu-dining.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIQmyC9M36lzfzQrZ7heI69q2x0YRTbzE',
    appId: '1:793243991391:ios:31c7a80010f84b7b064aea',
    messagingSenderId: '793243991391',
    projectId: 'cpu-dining',
    storageBucket: 'cpu-dining.appspot.com',
    iosClientId: '793243991391-jttdnngm1aj9ndccqeo80fe7kub8r2gd.apps.googleusercontent.com',
    iosBundleId: 'com.example.cpudining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIQmyC9M36lzfzQrZ7heI69q2x0YRTbzE',
    appId: '1:793243991391:ios:45a3059a9e921a80064aea',
    messagingSenderId: '793243991391',
    projectId: 'cpu-dining',
    storageBucket: 'cpu-dining.appspot.com',
    iosClientId: '793243991391-92guaq4qk68l8dvai86d1mg3794og9p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.cpudining.RunnerTests',
  );
}
